USE ECOMMERCE_ANALYTICS; 
SHOW TABLES;
-- DATA PRESENT IN THE TABLES
SELECT * FROM products;
SELECT * FROM orders;
SELECT * FROM order_items;
SELECT * FROM payments;
SELECT * FROM categories;
SELECT * FROM CUSTOMERS;