-- use ecommerce_analytics;
-- =========================================================
-- PHASE 6: ADVANCED SQL ANALYSIS
-- =========================================================

-- QUESTION 30:
-- RANK ALL CUSTOMERS BASED ON THEIR TOTAL SPENDING
-- FROM COMPLETED ORDERS.
SELECT CUSTOMER_NAME,TOTAL_SPENDING,DENSE_RANK() OVER(ORDER BY TOTAL_SPENDING DESC) AS RANKING FROM 
(
	SELECT C.CUSTOMER_NAME ,SUM(OT.QUANTITY*OT.UNIT_PRICE) AS TOTAL_SPENDING FROM CUSTOMERS C
	LEFT JOIN ORDERS O
	ON C.CUSTOMER_ID=O.CUSTOMER_ID
	JOIN ORDER_ITEMS OT
	ON O.ORDER_ID=OT.ORDER_ID
	WHERE O.ORDER_STATUS='completed'
	GROUP BY C.CUSTOMER_ID,C.CUSTOMER_NAME
) AS T;

-- QUESTION 31:
-- FIND THE TOP 3 CUSTOMERS WITH THE HIGHEST TOTAL SPENDING
-- USING A WINDOW FUNCTION.
SELECT CUSTOMER_NAME,TOTAL_SPENDING,RANKING FROM
(
	SELECT CUSTOMER_NAME,TOTAL_SPENDING,DENSE_RANK() OVER(ORDER BY TOTAL_SPENDING DESC) AS RANKING FROM 
	(
		SELECT C.CUSTOMER_NAME ,SUM(OT.QUANTITY*OT.UNIT_PRICE) AS TOTAL_SPENDING FROM CUSTOMERS C
		LEFT JOIN ORDERS O
		ON C.CUSTOMER_ID=O.CUSTOMER_ID
		JOIN ORDER_ITEMS OT
		ON O.ORDER_ID=OT.ORDER_ID
		WHERE O.ORDER_STATUS='completed'
		GROUP BY C.CUSTOMER_ID,C.CUSTOMER_NAME
	) AS T
) AS PP WHERE RANKING<=3;


-- QUESTION 32:
-- CALCULATE THE MONTHLY REVENUE FROM COMPLETED ORDERS
-- AND THE RUNNING TOTAL OF REVENUE THROUGHOUT THE YEAR.

SELECT ORDER_YEAR,ORDER_MONTH,MONTHLY_REVENUE,SUM(MONTHLY_REVENUE) OVER(ORDER BY ORDER_YEAR, ORDER_MONTH ) AS RUNNING_TOTAL FROM
(
	SELECT 
		YEAR(O.ORDER_DATE) AS ORDER_YEAR,
		MONTH(O.ORDER_DATE) AS ORDER_MONTH,
		SUM(P.AMOUNT) AS MONTHLY_REVENUE
	FROM ORDERS O
	JOIN PAYMENTS P
		ON O.ORDER_ID = P.ORDER_ID
	WHERE O.ORDER_STATUS = 'COMPLETED'
	GROUP BY YEAR(O.ORDER_DATE), MONTH(O.ORDER_DATE)
	ORDER BY ORDER_YEAR, ORDER_MONTH
) AS T;

-- QUESTION 33:
-- CALCULATE THE MONTHLY REVENUE FROM COMPLETED ORDERS
-- AND COMPARE EACH MONTH'S REVENUE WITH THE PREVIOUS MONTH'S REVENUE.

SELECT ORDER_YEAR,
       ORDER_MONTH,
       TOTAL_AMOUNT,
       LAG(TOTAL_AMOUNT) OVER(
           ORDER BY ORDER_YEAR, ORDER_MONTH
       ) AS LAGGING
FROM
(
    SELECT YEAR(O.ORDER_DATE) AS ORDER_YEAR,
           MONTH(O.ORDER_DATE) AS ORDER_MONTH,
           SUM(P.AMOUNT) AS TOTAL_AMOUNT
    FROM ORDERS O
    JOIN PAYMENTS P
        ON O.ORDER_ID = P.ORDER_ID
    WHERE O.ORDER_STATUS = 'COMPLETED'
    GROUP BY YEAR(O.ORDER_DATE), MONTH(O.ORDER_DATE)
    ORDER BY ORDER_YEAR, ORDER_MONTH
) AS SS;

-- QUESTION 34:
-- CALCULATE THE MONTH-OVER-MONTH REVENUE GROWTH PERCENTAGE
-- FOR COMPLETED ORDERS.

SELECT 
    ORDER_YEAR,
    ORDER_MONTH,
    TOTAL_AMOUNT,
    PREVIOUS_MONTH_REVENUE,
    ROUND(
        (TOTAL_AMOUNT - PREVIOUS_MONTH_REVENUE)
        / PREVIOUS_MONTH_REVENUE * 100,
        2
    ) AS GROWTH_PERCENTAGE
FROM
(
    SELECT 
        ORDER_YEAR,
        ORDER_MONTH,
        TOTAL_AMOUNT,
        LAG(TOTAL_AMOUNT) OVER (
            ORDER BY ORDER_YEAR, ORDER_MONTH
        ) AS PREVIOUS_MONTH_REVENUE
    FROM
    (
        SELECT 
            YEAR(O.ORDER_DATE) AS ORDER_YEAR,
            MONTH(O.ORDER_DATE) AS ORDER_MONTH,
            SUM(P.AMOUNT) AS TOTAL_AMOUNT
        FROM ORDERS O
        JOIN PAYMENTS P
            ON O.ORDER_ID = P.ORDER_ID
        WHERE O.ORDER_STATUS = 'COMPLETED'
        GROUP BY 
            YEAR(O.ORDER_DATE),
            MONTH(O.ORDER_DATE)
    ) AS MONTHLY_REVENUE
) AS REVENUE_COMPARISON;

-- QUESTION 35:
-- FIND THE HIGHEST-REVENUE PRODUCT WITHIN EACH PRODUCT CATEGORY
-- USING A WINDOW FUNCTION.

SELECT CATEGORY_NAME,PRODUCT_NAME,TOTAL_REVENUE,RANKING FROM (
	SELECT CATEGORY_NAME,PRODUCT_NAME,TOTAL_REVENUE,DENSE_RANK() OVER(PARTITION BY CATEGORY_NAME ORDER BY TOTAL_REVENUE DESC) AS RANKING FROM 
	(
		SELECT 
			C.CATEGORY_NAME,P.PRODUCT_NAME,
			SUM(OT.QUANTITY * OT.UNIT_PRICE) AS TOTAL_REVENUE
		FROM CATEGORIES C
		JOIN PRODUCTS P
			ON C.CATEGORY_ID = P.CATEGORY_ID
		LEFT JOIN ORDER_ITEMS OT 
			ON P.PRODUCT_ID = OT.PRODUCT_ID
		JOIN ORDERS O
			ON OT.ORDER_ID = O.ORDER_ID
		WHERE O.ORDER_STATUS = 'COMPLETED'
		GROUP BY C.CATEGORY_ID, C.CATEGORY_NAME,P.PRODUCT_ID
	)AS SS
) AS SI WHERE RANKING=1;