-- =========================================================
-- PHASE 4: CUSTOMER ANALYSIS
-- =========================================================

-- QUESTION 23:
-- HOW MANY ORDERS HAS EACH CUSTOMER PLACED?
SELECT C.CUSTOMER_NAME ,COUNT(*) AS ORDER_COUNT FROM CUSTOMERS C
LEFT JOIN ORDERS O
ON C.CUSTOMER_ID=O.CUSTOMER_ID
GROUP BY C.CUSTOMER_ID,C.CUSTOMER_NAME;

-- =========================================================
-- QUESTION 24:
-- HOW MUCH HAS EACH CUSTOMER SPENT ON COMPLETED ORDERS?
-- =========================================================
SELECT C.CUSTOMER_NAME ,SUM(OT.QUANTITY*OT.UNIT_PRICE) AS TOTAL_SPENDING FROM CUSTOMERS C
LEFT JOIN ORDERS O
ON C.CUSTOMER_ID=O.CUSTOMER_ID
JOIN ORDER_ITEMS OT
ON O.ORDER_ID=OT.ORDER_ID
WHERE O.ORDER_STATUS='completed'
GROUP BY C.CUSTOMER_ID,C.CUSTOMER_NAME;

-- =========================================================
-- QUESTION 25:
-- WHO IS THE CUSTOMER WITH THE HIGHEST TOTAL SPENDING
-- ON COMPLETED ORDERS?
-- =========================================================
SELECT C.CUSTOMER_NAME ,SUM(OT.QUANTITY*OT.UNIT_PRICE) AS TOTAL_SPENDING FROM CUSTOMERS C
LEFT JOIN ORDERS O
ON C.CUSTOMER_ID=O.CUSTOMER_ID
JOIN ORDER_ITEMS OT
ON O.ORDER_ID=OT.ORDER_ID
WHERE O.ORDER_STATUS='completed'
GROUP BY C.CUSTOMER_ID,C.CUSTOMER_NAME
ORDER BY TOTAL_SPENDING DESC LIMIT 1;

-- =========================================================
-- QUESTION 26:
-- WHICH CUSTOMERS HAVE PLACED MORE THAN 5 ORDERS?
-- =========================================================
SELECT C.CUSTOMER_NAME , COUNT(O.ORDER_ID) AS PLACED_ORDERS FROM CUSTOMERS C 
LEFT JOIN ORDERS O
ON C.CUSTOMER_ID=O.CUSTOMER_ID
GROUP BY C.CUSTOMER_ID
HAVING PLACED_ORDERS >5 ;

-- =========================================================
-- QUESTION 27:
-- WHICH CUSTOMERS HAVE SPENT MORE THAN THE AVERAGE
-- CUSTOMER SPENDING ON COMPLETED ORDERS?
-- =========================================================
SELECT 
    C.CUSTOMER_NAME,
    SUM(OT.QUANTITY * OT.UNIT_PRICE) AS TOTAL_SPENDING
FROM CUSTOMERS C
JOIN ORDERS O
    ON C.CUSTOMER_ID = O.CUSTOMER_ID
JOIN ORDER_ITEMS OT
    ON O.ORDER_ID = OT.ORDER_ID
WHERE O.ORDER_STATUS = 'COMPLETED'
GROUP BY C.CUSTOMER_ID, C.CUSTOMER_NAME
HAVING SUM(OT.QUANTITY * OT.UNIT_PRICE) >
(
    SELECT AVG(CUSTOMER_SPENDING)
    FROM
    (
        SELECT 
            O.CUSTOMER_ID,
            SUM(OT.QUANTITY * OT.UNIT_PRICE) AS CUSTOMER_SPENDING
        FROM ORDERS O
        JOIN ORDER_ITEMS OT
            ON O.ORDER_ID = OT.ORDER_ID
        WHERE O.ORDER_STATUS = 'COMPLETED'
        GROUP BY O.CUSTOMER_ID
    ) AS CUSTOMER_TOTALS
);

-- QUESTION 28:
-- FIND CUSTOMERS WHO HAVE PLACED AT LEAST ONE ORDER BUT HAVE NEVER PLACED A COMPLETED ORDER.
SELECT C.CUSTOMER_NAME,
       COUNT(O.ORDER_ID) AS TOTAL_ORDERS
FROM CUSTOMERS C
JOIN ORDERS O
    ON C.CUSTOMER_ID = O.CUSTOMER_ID
GROUP BY C.CUSTOMER_ID, C.CUSTOMER_NAME
HAVING COUNT(O.ORDER_ID) > 0
   AND COUNT(CASE WHEN O.ORDER_STATUS = 'completed' THEN 1 END) = 0;
   
-- QUESTION 29:
-- FIND THE CUSTOMER WHO HAS PLACED THE MOST ORDERS IN THE E-COMMERCE PLATFORM.
SELECT C.CUSTOMER_NAME,
       COUNT(O.ORDER_ID) AS TOTAL_ORDERS
FROM CUSTOMERS C
JOIN ORDERS O
    ON C.CUSTOMER_ID = O.CUSTOMER_ID
GROUP BY C.CUSTOMER_ID, C.CUSTOMER_NAME
ORDER BY TOTAL_ORDERS DESC LIMIT 1;